### ISSUE TITLE
Is this repository abandoned?

### ISSUE THREAD

**Issue by Rapsssito** [tradle/react-native-udp#101]

**Comment by mvayngrib** [comment]
@Rapsssito not abandoned, but it is not being actively maintained. I have little time to dedicate to this, but if you want to send some PRs, and seems it's the same case with @aprock

**Comment by Rapsssito** [comment]
@mvayngrib I asked because there are a few PRs that I would really like to see merged. However, they seem to have been waiting for a long time. Is there a possibility to add another maintainer to the repo?

**Comment by mvayngrib** [comment]
@Rapsssito which PRs specifically? Can you please comment on the ones u'd like merged what specifically u tested?

> Is there a possibility to add another maintainer to the repo?

yep, though i'd prefer to have the person make/test a few PRs before making them maintainer

**Comment by Rapsssito** [comment]
I have been using PRs #97 and #95 with this repo master branch without issues. It would be great if you could publish an update to npm, at least with the master branch changes.

**Comment by Fr33maan** [comment]
@mvayngrib hey mate, any chance to make @Rapsssito maintainer ? He is active on the repo and have made important PRs.
This package is the only UDP stuff on RN and it would be very nice to bring some activity on it. It has 5000 downloads a week, that's a lot of people to take care of and we all understand you don't have much time. <3
