### ISSUE TITLE
Can you designate a maintainer as you don't have time please ?

### ISSUE THREAD

**Issue by Fr33maan** [tradle/react-native-udp#115]

**Comment by Fr33maan** [comment]
@Rapsssito

**Comment by mvayngrib** [comment]
@Fr33maan done. @Rapsssito you should see an invite :) sorry for the long wait, i kept thinking i'd have more time to review and test stuff

**Comment by Fr33maan** [comment]
Good job ! You just gave a chance to this lib to have a long life ! <3
