### ISSUE TITLE
Base64 encoded messages before sent to bridge

### ISSUE THREAD

**Issue by Fr33maan** [tradle/react-native-udp#116]
Messages are received from the socket, base64 encoded, passed through the bridge then they are decoded in JS before being sent with an event emitter.

Encoding Java -> https://github.com/tradle/react-native-udp/blob/master/android/src/main/java/com/tradle/react/UdpReceiverTask.java#L48
Encoding Objective-C -> https://github.com/tradle/react-native-udp/blob/master/ios/UdpSockets.m#L131
Decoding -> https://github.com/tradle/react-native-udp/blob/master/UdpSocket.js#L133

I wonder if we can get rid of this double operation and simply pass the byte array to the application without any transaformation.

EDIT:
I understand that we can only pass JSON types values through the bridge. Then we have choice to serialize `byte[]` either with base64 or array of int (maybe short uint ?).
For my specific use case, int would be better so I can directly use them in the program and avoid a serialize/deserialize roundtrip.
I also believe than the deserializing stuff on the JS side, after the data passed the bridge should be handled by the user of the lib instead of the lib itself.
Typically, I would remove the `base64.toByteArray()` and directly send the base64 string in the event instead of the `Uint8Array`

**Comment by Rapsssito** [comment]
I will take a look at the code, I am a little busy right now. I will get to you ASAP.

**Comment by Fr33maan** [comment]
I had a deep look on how it's working and base64 is the best way to pass data through the bridge
