### ISSUE TITLE
Allow for hostnames

### ISSUE THREAD

**Issue by ajwhite** [tradle/react-native-udp#12]
Currently IP addresses are required for `socket.send`.

It'd be great if we could provide a hostname as well. Currently I've added a native function to derive the IP from a hostname in order to satisfy the IP requirement for `react-native-udp`

**Comment by mvayngrib** [comment]
@ajwhite happy to accept PRs!

**Comment by ajwhite** [comment]
You betcha, that's why I threw it up here :) I don't have time at the moment, but hopefully someone in the community could pick this up, otherwise sometime in the future I can take a look.

Cheers :smile:

**Comment by mvayngrib** [comment]
@ajwhite sound good. Actually it looks like at least for iOS, all we need to do is replace isValidIP in UdpSocket.js with isValidIpOrHost (and respective regex), as on the ios side, GCDAsyncUdpSocket accepts hostnames as well as ips.

**Comment by aprock** [comment]
it's the same with the android side. @mvayngrib

**Comment by mvayngrib** [comment]
@aprock glad to hear that :)

**Comment by ajwhite** [comment]
Oh sweet -- just so I am understanding correctly, the sockets can already accept hostnames as well as IPs -- we just need to update [the validation](https://github.com/tradle/react-native-udp/blob/master/UdpSocket.js#L272-L276) to accept hostnames?

If so, I may just throw a PR up now

**Comment by aprock** [comment]
yes
