### ISSUE TITLE
setMulticastInterface is not a function

### ISSUE THREAD

**Issue by rishav95** [tradle/react-native-udp#122]
https://nodejs.org/api/dgram.html#dgram_example_ipv4_outgoing_multicast_interface

is this not available through this library?
i can see it in the socket class inside dgram.d.ts though...

**Comment by Fr33maan** [comment]
This lib is an interface to android and ios native UDP socket even if it advertise for being an implementation of dgram.

**Comment by Rapsssito** [comment]
@rishav95, sorry about that. The TS declaration file is taken form the original dgram API. We are working on a TS declaration file with the just available API.
