### ISSUE TITLE
'GCDAsyncUdpSocket.h' file not found

### ISSUE THREAD

**Issue by CCSWXD** [tradle/react-native-udp#123]
react-native-udp 2.7.0
"react-native": "0.58.6",  
![image](https://user-images.githubusercontent.com/19770788/86505327-a9b3ee00-bdf5-11ea-8637-2e82cc8d4129.png)

**Comment by Rapsssito** [comment]
@CCSWXD, it looks like you have not installed all the pods or Xcode is not able to find them.
