### ISSUE TITLE
add expo docs

### ISSUE THREAD

**Issue by zwhitchcox** [tradle/react-native-udp#127]
Hi, I'm not sure if you already have [expo](https://expo.io) documented somewhere, but the development experience is superb, and that's actually [react-native's recommended way to set up the development environment now](https://reactnative.dev/docs/environment-setup). It would be great if you could make expo-specific installation instructions, because the current installation instructions don't really apply. There is no `android` directory in the main directory, and the `UdpSocketsModule` does not get installed automatically.

In the meantime, I guess I should just use the `react-native-cli`?

**Comment by mvayngrib** [comment]
@zwhitchcox afaik expo doesn't allow adding custom native modules, so u may need to eject

**Comment by zwhitchcox** [comment]
You are correct, you have to "eject"...Just for me, it would've been helpful still if that were in the README though, just a suggestion. Thanks for the info!

**Comment by struank-l** [comment]
If anyone else comes across this ejecting is no longer necessary, but you do need to run `npx expo prebuild`
