### ISSUE TITLE
 I can't receive packages on motorola devices

### ISSUE THREAD

**Issue by Hugogsalas** [tradle/react-native-udp#130]
I read that the devices of this brand need change the socket type to multicast socket, but i cant makead work, somone know how give support to this devices?

I tring adding this code in UdpSocketsModule.java archive

```
WifiManager wifi = (WifiManager)reactContext.getApplicationContext().getSystemService( Context.WIFI_SERVICE );
        if(wifi != null){
            WifiManager.MulticastLock lock = wifi.createMulticastLock("Log_Tag");
            lock.acquire();
}
```

and replace DatagramSocket to MulticastSocket

**Comment by Rapsssito** [comment]
@Hugogsalas, react-native-udp already uses MulticastSocket under the hood. Can you test your code on other device to test if the issue is reproducible there?

**Comment by Hugogsalas** [comment]
Hi @Rapsssito, yes I tested my app in a Motrola Z3 Play and Motrola G5, but I couldnt received packages, i test my app in a Redmi Note 7 and IPhone SE 2th generathion  and all works great.

**Comment by Rapsssito** [comment]
@Hugogsalas, I don't own any Motorola devices to test with. Have you tested the [example app](https://github.com/tradle/react-native-udp/tree/master/examples/udpsockets) with those devices?
