### ISSUE TITLE
"No overload" on socket.send(string, number, string, function)

### ISSUE THREAD

**Issue by Cazfri** [tradle/react-native-udp#132]
## Description
`socket.send()` seems to be incorrectly overloaded when used in a React Native Typescript app. See below for details. 

## Steps to reproduce
My code:
```typescript
import dgram from "react-native-udp";
...
sendMessage() {
  let socket = dgram.createSocket('udp4');
  socket.send("abcd", 64456, "127.0.0.1", (err: Error) => {
    if (err) throw err;
    console.log('message sent');
  });
}
```

## Current behavior
My IDE (VSCode) shows an error on the code above, complaining about an overload error on the 3rd parameter:

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '"127.0.0.1"' is not assignable to parameter of type 'number'. ts(2769)

index.d.ts(58, 7): The last overload is declared here.
```

When I try to run the code on an Android emulator, I get the error `Error: invalid port`. Probably because my address (string) is trying to be interpreted as the port (number).

## Expected behavior
The arguments `string, number, string, function(Error) => void ` should use the `msg, port, addr, callback` overload, but it seems to be trying to use a different overload. Perhaps it is defaulting to the `msg, offset, length, callback` overload?

Unfortunately I'm quite new to React Native and Typescript so I can't offer any fixes, but I'm happy to try out possible solutions if need be.

**Screenshots**
[Screenshot of error given by IDE](https://imgur.com/MjB1lHG)
[Screenshot of error when run on Android emulator](https://imgur.com/PqUiXL6)

## Relevant information
| | |
| ----------- | --- |
| OS | macOS 10.15.6   |
| AVD | Pixel 3a API 28, Android 9.0  |
| react-native | 4.12.0   |
| react-native-udp  | 3.2.0   |

**Comment by Rapsssito** [comment]
@Cazfri, sorry your are having that issue. The complete `socket.send()` interface is the following:
```js
/**
   * socket.send(buf, offset, length, port, address, [callback])
   *
   * For UDP sockets, the destination port and IP address must be
   * specified. A string may be supplied for the address parameter, and it will
   * be resolved with DNS. An optional callback may be specified to detect any
   * DNS errors and when buf may be re-used. Note that DNS lookups will delay
   * the time that a send takes place, at least until the next tick. The only
   * way to know for sure that a send has taken place is to use the callback.
   *
   * If the socket has not been previously bound with a call to bind, it's
   * assigned a random port number and bound to the "all interfaces" address
   * (0.0.0.0 for udp4 sockets, ::0 for udp6 sockets).
   *
   * @param {Array|string} message to be sent
   * @param {number} offset Offset in the buffer where the message starts.
   * @param {number} length Number of bytes in the message.
   * @param {number} port destination port
   * @param {string} address destination IP
   * @param {function} callback Callback when message is done being delivered.
   *                            Optional.
   */
  send(buffer, offset, length, port, address, callback)
```

You are missing the `offset` param. In your case, you will have to call:
```js
socket.send("abcd", 0, 64456, "127.0.0.1", (err: Error) => {});
```

I am working on a complete refresh of the declaration files and JS documentation in order to prevent this kind of issues. I hope this helps with your problem!

**Comment by Cazfri** [comment]
Gotcha, thanks for the quick response. The code you suggested failed with a similar error, but adding the size parameter works for me 😃.

It seems that index.d.ts includes a [function declaration](https://github.com/tradle/react-native-udp/blob/master/index.d.ts#L53) where the parameters are option. Would that be removed in a "complete refresh of the declaration files"?

**Comment by Rapsssito** [comment]
@Cazfri, you are right, sorry, I messed up the `port` with `length` parameters. Glad it worked!

**The "refresh" will include a complete reconstruction of the declaration file (`index.d.ts`) taking the JS as base**, so everything will match up with the JS interface. This repository has been running on almost zero-maintenance. I was recently given maintainer permissions and I'm trying to give it a facelift and keep it updated. The `index.d.ts` was kind of a _we-need-that-patch-right-now_ in order to have some TypeScript support (it is almost a copy from node's `dgram` declaration file).

**Comment by Cazfri** [comment]
Great, glad to hear, I'm excited to see what comes next. Again, thanks for the quick response. I'm glad to see someone is maintaining and paying attention to this library.
