### ISSUE TITLE
TypeError: null is not an object (evaluating 'Sockets.createSocket') when creating socket

### ISSUE THREAD

**Issue by alloygoh** [tradle/react-native-udp#134]
## Description

When following the example given, a TypeError is thrown. Looking at the error shown on the AVD, the error seems to be coming from `UdpSocket.js` line 53. The error shown is `null is not an object`. It seems that NativeModules.UdpSockets is undefined.

## Steps to reproduce
1. import the library
2. attempt to create a `upd4` socket
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/32241418/91656828-8dc78280-eaee-11ea-866d-42f205b2a3b5.png)

## Relevant information
|             |     |
| ----------- | --- |
| OS | Android  |
| react-native | 0.63.2   |
| react-native-udp  | ^3.2.0   |

**Comment by Rapsssito** [comment]
@alloygoh, it looks like an error on the React Native linking. Shut everything down and check this solutions:
* Reinstall `react-native-udp`
* Reset metro's cache: `yarn start --reset-cache`
* Android: `cd android; ./gradlew clean; cd ..`
* iOS: `cd ios; pod install; cd ..`

If it does not work, try removing and reinstalling your node-modules folder.

**Comment by ollolollollooloo** [comment]
still happening...

**Comment by Rapsssito** [comment]
@ollolollollooloo, does the [example code](https://github.com/tradle/react-native-udp/tree/master/examples/udpsockets) work for you?

**Comment by Alkaige** [comment]
@Rapsssito I've got the same error when creating a new project using expo, with adding the example code in `componentDidMount` function of my App.

react-native-udp 4.1.2, expo sdk 40.0.0.

Thanks for helping !

**Comment by Rapsssito** [comment]
@Alkaige, you might have to "eject" your expo project in order to use this native custom module.

**Comment by ollolollollooloo** [comment]
@Rapsssito doesnt

**Comment by alexweininger** [comment]
+1 Happening to me as well.

**Comment by ollolollollooloo** [comment]
check this out
https://www.youtube.com/watch?v=EfbRKaPt2S4

**Comment by idabaicai** [comment]
use react-native@0.63.2 works for me

**Comment by nitinsane** [comment]
anybody able to solve this?

**Comment by dkornilove** [comment]
> [@alloygoh](https://github.com/alloygoh), it looks like an error on the React Native linking. Shut everything down and check this solutions:
> 
> * Reinstall `react-native-udp`
> * Android: `cd android; ./gradlew clean; cd ..`
> * iOS: `cd ios; pod install; cd ..`
> * Reset metro's cache: `yarn start --reset-cache`
> 
> If it does not work, try removing and reinstalling your node_modules folder.

tried all of this this, still an issue
android, RN 0.74.1
