### ISSUE TITLE
TypeError: dgram.createSocket is not a function

### ISSUE THREAD

**Issue by Shing-Ho** [tradle/react-native-udp#136]
## Description
TypeError: dgram.createSocket is not a function. (In 'dgram.createSocket('udp4')', 'dgram.createSocket' is undefined)

## Steps to reproduce
1. Install latest react-native-udp and react-native-ssdp
2. Also, react-native version is latest
3. run metro bundler and open app
4. got this error in console

Or code:
```js
// Your code
```

## Relevant information
|             |     |
| ----------- | --- |
| OS | macOS Catalina 10.15.6   |
| react-native | 0.63.2   |
| react-native-udp  | 4.0.1   |

**Comment by Rapsssito** [comment]
@Shing-Ho, make sure to install all pods, run `cd ios; pod install; cd ..`.

**Comment by Shing-Ho** [comment]
@Rapsssito Thank you for quick update. I can surely tell you I did `pod install`.

**Comment by Rapsssito** [comment]
@Shing-Ho, it looks like a linking error. Make sure everything is imported correctly. Does #134 reproduce your error?

**Comment by Shing-Ho** [comment]
Ofc, I tried to reinstall react-native-udp several times

**Comment by Rapsssito** [comment]
@Shing-Ho, could you provide your `package.json`?

Also, make sure you are calling `react-native-udp` as shown in the [documentation](https://github.com/tradle/react-native-udp#usage).

**Comment by Shing-Ho** [comment]
```
{
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.12.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/slider": "^3.0.3",
    "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "dropbox": "^4.0.30",
    "fast-xml-parser": "^3.17.4",
    "i18n-js": "^3.7.1",
    "query-string": "^6.13.1",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-audio-record": "^0.2.2",
    "react-native-audio-recorder-player": "^2.5.3",
    "react-native-check-box": "^2.1.7",
    "react-native-contacts": "^5.2.7",
    "react-native-event-listeners": "^1.0.7",
    "react-native-fingerprint-scanner": "^6.0.0",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-modal": "^11.5.6",
    "react-native-modal-dropdown": "git+https://github.com/irekrog/react-native-modal-dropdown#fix/bump-version-deprecated-react-native-listview",
    "react-native-network-info": "^5.2.1",
    "react-native-nfc-manager": "^2.1.9",
    "react-native-reanimated": "^1.13.0",
    "react-native-root-toast": "^3.2.1",
    "react-native-safe-area-context": "^3.1.7",
    "react-native-screens": "^2.10.1",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-sound-recorder": "^1.4.0",
    "react-native-spinkit": "^1.5.0",
    "react-native-sqlcipher-storage": "git+https://github.com/axsy-dev/react-native-sqlcipher-storage#autolinking",
    "react-native-ssdp": "git+https://github.com/amostap/react-native-ssdp.git",
    "react-native-swiper": "^1.6.0",
    "react-native-udp": "^4.0.1",
    "react-native-vector-icons": "^7.0.0",
    "react-native-version-number": "^0.3.6",
    "react-native-web-swiper": "git+https://github.com/Shing-Ho/react-native-web-swiper",
    "react-native-webview": "^10.8.3",
    "rn-fetch-blob": "^0.12.0",
    "socket.io-client": "^2.3.0",
    "swr": "^0.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

Also, I am not using react-native-udp directly. I am using react-native-ssdp and it is using react-native-udp

**Comment by Rapsssito** [comment]
@Shing-Ho, `react-native-ssdp` uses an old version of `react-native-udp`. You must add a `react-native-udp` version lower than 3.0.0 to your project.

**Comment by Shing-Ho** [comment]
Hmm, That sounds right.

**Comment by Rapsssito** [comment]
@Shing-Ho, I am working on a backwards-compatibility update, I might release it today. I will update you as soon as it is released.

**Comment by Shing-Ho** [comment]
Thank you!~

**Comment by namitonefc** [comment]
We are still facing this issue with **react-native-upd 4.0.2**.

Its happening with https://github.com/artem-russkikh/react-native-ntp-client.

`TypeError: dgram.createSocket is not a function. (In 'dgram.createSocket("udp4")', 'dgram.createSocket' is undefined)`

This is located in ntp-client.js:39:21

```
var client = dgram.createSocket("udp4"),
ntpData = new Buffer(48);
```

Will appreciate any help on this. This issue has become a blocker for us. Thanks.

**Comment by Rapsssito** [comment]
@namitonefc, **if it still doesn't work, try using react-native-udp@2.6.1**. You may also post a PR fixing react-native-udp import in react-native-ntp-client.
