### ISSUE TITLE
Crash: Task android.os.AsyncTask rejected from java.util.concurrent.ThreadPoolExecutor

### ISSUE THREAD

**Issue by hubciorz** [tradle/react-native-udp#143]
## Description
App crashes after going to background, closing socket, going to foreground and open socket again (Android)

## Error
```java
com.tradle.react.UdpSockets.close
UdpSockets.java, line 285
java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@fd47a96 rejected from java.util.concurrent.ThreadPoolExecutor@d61617[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 513]
```

## Stack traces
```java
java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution ThreadPoolExecutor.java:2014
java.util.concurrent.ThreadPoolExecutor.reject ThreadPoolExecutor.java:794
java.util.concurrent.ThreadPoolExecutor.execute ThreadPoolExecutor.java:1340
android.os.AsyncTask.executeOnExecutor AsyncTask.java:607
com.tradle.react.UdpSockets.close UdpSockets.java:285
java.lang.reflect.Method.invoke Method.java
com.facebook.react.bridge.JavaMethodWrapper.invoke JavaMethodWrapper.java:372
com.facebook.react.bridge.JavaModuleWrapper.invoke JavaModuleWrapper.java:151
com.facebook.react.bridge.queue.NativeRunnable.run NativeRunnable.java
android.os.Handler.handleCallback Handler.java:739
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage MessageQueueThreadHandler.java:27
android.os.Looper.loop Looper.java:158
com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run MessageQueueThreadImpl.java:226
java.lang.Thread.run Thread.java:818
```

## Steps to reproduce
1. Open a socket, setBroadcast(true), addMembership("239.255.255.250")
2. Go to background and close socket (by detecting AppState change)
3. Go to foreground and open socket again
4. Wait.

Code:
```js
  this.udpSocket = createSocket({ type: "udp4", reuseAddr: true })
  this.udpSocket.on("message", this.onUdp.bind(this))
  this.udpSocket.on("error", this.onUDPError.bind(this))
  this.udpSocket.on("listening", this.onUDPListening.bind(this))
  this.udpSocket.bind(7979)

  private onUDPListening(err) {
    if (err) {
      log.error("Error when listening on UDP discovering socket:", err)
      return
    }

    if (this.udpSocket) {
      log.debug("Setting multicast for socket:", this.udpSocket)
      this.udpSocket.setBroadcast(true)
      this.udpSocket.addMembership(MULTICAST_GROUP)
    } else {
      log.debug("Error when setting multicast for socket. Socket is null")
    }
  }

  private onUDPError(err) {
    log.error("Error on UDP discovering socket:", err)
  }

...
// AppState change detection logic
```
## Current behavior
App crashes on some devices with multiple Android versions. Sometimes the error is not in `com.tradle.react.UdpSockets.didReceiveData` but `com.tradle.react.UdpSockets.close`. **It's not 100% reproducible** 

Sometimes we can see in the logs `no client found with id x` (which is related to #118)

## Expected behavior
App does not crash - event if there is an error, it should be passed in "error" callback somehow.

## Relevant information
|             |     |
| ----------- | --- |
| react-native | 0.62.1   |
| react-native-udp  | 4.0.3 (but happens on earlier versions, too)   |

## Occurred on
|             |     |
| ----------- | --- |
| Device | OS   |
| Honor 6x  | Android 7.0   |
| Galaxy J5(2016)  | Android 6.0.1   |
| Xperia Z5 Compact  | Android 7.1.2  |
| P20 lite  | Android 9  |

**Comment by Rapsssito** [comment]
I will close this issue since it is likely related to #144. The same update might fix both issues. If you continue experiencing this problems after the fix, feel free to reopen the issue.
