### ISSUE TITLE
Cleaning up sockets when bridge reloads

### ISSUE THREAD

**Issue by ajwhite** [tradle/react-native-udp#15]
For those of us using integrations like [Code Push](https://github.com/Microsoft/react-native-code-push), or when some of us reload the bridge during uncaught exceptions to avoid full crashes.

When a bridge reloads, the [`instances`](https://github.com/tradle/react-native-udp/blob/master/UdpSocket.js#L27) value is going to reset back to `0`, and a new socket will be created with an `_id` of `0`, even though on the native side that socket ID already exists.

Couple thoughts on this:
- Clean up sockets when the bridge reloads (if there's some way to observe this event)
- Move the `id` generation onto the native side as part of `createSocket`, and return that `id` back down to the JS context.

**Comment by ajwhite** [comment]
For a temporary fix on my fork, I think i'm going to do a "get or create" -- if the socket for an ID already exists, it'll use that, otherwise it'll create it.

I'm only dealing with 1 socket right now, so it's pretty deterministic. I won't provide this as a solution for this project, but as a stop gap, I think i'm going to do that to avoid the exception.

**Comment by mvayngrib** [comment]
@ajwhite on the iOS side, we have:

```
+ (void) initialize {
  [[NSNotificationCenter defaultCenter] addObserver:self
                                           selector:@selector(closeAllSockets)
                                               name:RCTReloadNotification
                                             object:nil];
}
```

does this address the problem you're experiencing? @aprock do we have something like this for android?

**Comment by ajwhite** [comment]
On android you guys [do close all client sockets](https://github.com/tradle/react-native-udp/blob/master/android/src/main/java/com/tradle/react/UdpSockets.java#L57-L81) as well.

Hrmm. So it sounds like there is proper cleanup

**Comment by ajwhite** [comment]
![screen shot 2015-12-21 at 7 05 01 pm](https://cloud.githubusercontent.com/assets/656630/11944658/c2865ddc-a815-11e5-82e1-2d6bf56d9f27.png)

**Comment by ajwhite** [comment]
As a note -- this appears to only happen during `bind` -- if I remove the `bind` call, and only use `send`, we're all good.
