### ISSUE TITLE
Peer address can be randomly returned as hostname or IP depending on DNS availability

### ISSUE THREAD

**Issue by labteam** [tradle/react-native-udp#155]
## Description
In my application, I use the IP address to identify a peer who replied to me. And in 99% of my customers once I received a message it comes with IP address and for 1% it comes with hostname like ambivision.broadband which is not proper in our case and there is no way to get the IP address instead of a hostname (I could ask DNS for the IP using another lib). 
That's a piece of code that cause it:
` final InetAddress address = packet.getAddress();
                final String base64Data = Base64.encodeToString(packet.getData(), packet.getOffset(),
                    packet.getLength(), Base64.NO_WRAP);
                receiverListener.didReceiveData(base64Data, **address.getHostName()**, packet.getPort());
                `

## Steps to reproduce
Just use a sample code and display the host address. It happens only if local DNS works well and can return hostname.

Or code:
```js
// Your code
Use an example from the main website. 
```

## Current behaviour
Return IP address in most the situations and sometimes there is a hostname as an output.

## Expected behaviour
It should provide the IP address and hostname. Not one of them only and I think that the IP address should be prioritized. But give more options to the user.

## Relevant information
| router| I think it is connected with router settings as well - some of the customers have no problems, some does |
| OS | Mainly Android  |
| react-native | 0.61  |
| react-native-udp  | 2.6.1   |

**Comment by Rapsssito** [comment]
@labteam I don't understand your problem. Could you provide an example of the expected output and the one you get?
