### ISSUE TITLE
Getting TCP Conn 0x2821b1810 Failed : error 0:61 [61] on iOS

### ISSUE THREAD

**Issue by skoky** [tradle/react-native-udp#156]
## Description
I have used the code from README in my app. It works fine on Android, but once deployed on iPhone, I am getting "TCP Conn 0x2821b1810 Failed : error 0:61 [61]" error.

## Steps to reproduce
1. use example from README.md
2. deploy to iPhone
3. see console for errors

Or code:
```js
  const socket = dgram.createSocket({
        type: 'udp4',
        debug: true,
    })
    socket.bind(BROADCAST_PORT)
    socket.once('listening', function () {
        socket.send(MSG, undefined, undefined, BROADCAST_PORT, BROADCAST_ADDR, function (err) {
            if (err) console.log("ERR:"+err)
        })
    })

```

## Current behavior
UDP message is not sent

## Expected behavior
UDP message should be sent to network

## Relevant information
|             |     |
| ----------- | --- |
| iOS | 14.3   |
| react-native | 0.63.4   |
| react-native-udp  | 4.1.2   |

**Comment by skoky** [comment]
Also getting this in in log 

socket-5 failed to bind [Error: Error in bind() function]
Error: Error in bind() function

**Comment by Rapsssito** [comment]
@skoky, could you use the following code to provide an error trace:
```js
socket.bind(PORT, function(err) {
      if (err) throw console.log(err);
    });
```

**Comment by skoky** [comment]
II tried the code but I don't see any error now

**Comment by Rapsssito** [comment]
@skoky, the problem might not be related to this module since it looks like an TCP error.
