### ISSUE TITLE
React-native-udp library much slower than native android

### ISSUE THREAD

**Issue by baharb** [tradle/react-native-udp#161]
UDP performance is much critical for my application as it is a UI for real-time controller.
But the UDP response time performance has made me roll back to develop android and IOS application separately.
Basically, after all changes I could have done in using this UDP library of react-native, 
sending and receiving a packet will take in average 200 msec (from 80 msec to 550 msec) comparing to around 40 msec in a similar application in android platform.

react-native: 0.57.2
react-native-udp: 2.3.1

**Comment by Rapsssito** [comment]
@baharb, that makes sense since React Native uses a "bridge" to communicate with the native libraries. With the addition of "turbo-modules" this response time might be able to decrease.
