### ISSUE TITLE
Does the library implement queue for sockets?

### ISSUE THREAD

**Issue by baharb** [tradle/react-native-udp#163]
I have a real time application that uses react native udp. my application send packets every 1000 msec. What is the best way of using this library for my purpose?
Does the library implement queue for sockets? And I can use one socket for all packets (if it's possible) ?
Or I've to create a socket for every packet and close it in the end of receive response?

**Comment by Rapsssito** [comment]
@baharb, you should create one socket and send a package each time with the **same socket**. You could use `setInterval()` for this purpose.

**Comment by baharb** [comment]
> @baharb, you should create one socket and send a package each time with the **same socket**. You could use `setInterval()` for this purpose.

@Rapsssito , tnx for reply.
I had implemented this, but there is a problem.
If I create a socket, and bind that, I can't bind that socket any more, for other packets. (Error: Socket is already bound )
If I bind one time, when the socket was created, the app stop sending packets.

**Comment by Rapsssito** [comment]
@baharb, binding is only valid for one port. Try to rework your app so your packets can be sent to the same port so you can reuse the same socket.
