### ISSUE TITLE
UDP only received first message on ios 14

### ISSUE THREAD

**Issue by nguyenvanquan7826** [tradle/react-native-udp#164]
## Description
Hi, I use this lib, but when run on ios 14, udp socket only received first message. I must restart app to listen again. Please help fix it.

**Comment by gibo77** [comment]
Did you close right away? Do a Promise and return wait before you close so you can get all the messages. Remember UDP is an asynchronous operation.

**Comment by nguyenvanquan7826** [comment]
No, I don't close socket until close app. I want listen many UDP message.

**Comment by nguyenvanquan7826** [comment]
No, this bug is still on.
