### ISSUE TITLE
Android: undefined is not an object (evaluating 'Sockets.createSocket')

### ISSUE THREAD

**Issue by coconup** [tradle/react-native-udp#19]
I'm fairly new to this so it can be I'm doing something wrong. I set up a new react native project and installed react-native-udp (tried both by following the readme and through rn-nodeify). 

I then pasted this sample code within my render function to see if things would work:

`var dgram = require('react-native-udp')`
`var socket = dgram.createSocket('udp4')`
`socket.bind(12345)`

When starting up the AVD emulator, I get this error thrown at UdpSocket.js line 59:

`undefined is not an object (evaluating 'Sockets.createSocket')`

**Comment by mvayngrib** [comment]
Did you link the library? Run this from the command line: rnpm link

On Friday, June 10, 2016, coconup <notifications@github.com> wrote:

> I'm fairly new to this so it can be I'm doing something wrong. I set up a
> new react native project and installed react-native-udp (tried both by
> following the readme and through rn-nodeify).
>
> I then pasted this sample code within my render function to see if things
> would work:
>
> var dgram = require('react-native-udp')
> var socket = dgram.createSocket('udp4')
> socket.bind(12345)
>
> When starting the up in the AVD emulator, I get this error thrown at
> UdpSocket.js line 59:
>
> undefined is not an object (evaluating 'Sockets.createSocket')
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tradle/react-native-udp/issues/19>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAFH7OchbF8IS6JTEvsXrb291YVgUGBsks5qKSrNgaJpZM4Iyw3A>
> .
>


-- 
Mark Vayngrib
CTO & Co-founder
http://tradle.io
UK: +44 (0)7490 453346
US: +1 (201) 925-6626

**Comment by coconup** [comment]
That worked of course, thanks a lot for the support! Maybe it would be good to add this step to the readme in case other noobs like me get stuck at the same point :)
