### ISSUE TITLE
Getting error while executing the code

### ISSUE THREAD

**Issue by anagharamane** [tradle/react-native-udp#203]
## Description
Getting error while executing the code 

## Steps to reproduce
Just ran the command -  npx react-native run-android

**Screenshots**
![Error](https://user-images.githubusercontent.com/32288428/158018639-b78caee2-7ba3-4ca7-87ae-7afb7b38c497.PNG)

**Comment by Rapsssito** [comment]
Should be fixed by #205, feel free to reopen this issue if the problem persists.
