### ISSUE TITLE
Error createSocket undefined

### ISSUE THREAD

**Issue by NunoNogueira99** [tradle/react-native-udp#206]
Good night
I was trying to use this library in react native with expo but when I run it I get the following error

![WhatsApp Image 2022-04-10 at 20 08 09](https://user-images.githubusercontent.com/58145881/162637406-83010d92-7460-43f7-af95-c15f746f7dec.jpeg)

I'm running the example code

Could you help me to solve this situation since the error is inside a library file

**Comment by dougcooper** [comment]
still an issue

**Comment by buiducnhat** [comment]
Sill an issue

**Comment by buiducnhat** [comment]
Hi guys, after some days, I found a temporary solution to fix this problem for me.
I just run
```bash
npx react-native link react-native-udp
```
although I use react-native version 0.64 (>0.60)
