### ISSUE TITLE
null is not an object (evaluation 'Sockets.createSocket') error occuring when I try to create a socket (using expo react native latest version)

### ISSUE THREAD

**Issue by AdrianV2552** [tradle/react-native-udp#228]
## Description
the error "null is not an object (evaluation 'Sockets.createSocket')" is showing up when I try to create the socket using the line "const socket = dgram.createSocket('udp4')".

## Steps to reproduce
1. Start expo react native project on latest version
2. try to import "react-native-udp" 
3. try to run this line of code

code:

import { useNavigation } from '@react-navigation/core'//maybe @react-navigation/core
import { StyleSheet, Text, TouchableOpacity, View, Dimensions } from 'react-native'
import React from 'react'
import { auth } from '../firebase'
import MapView, {circle, PROVIDER_GOOGLE, Marker} from 'react-native-maps';
import { locations } from '../Data/Data';
//import dgram from 'react-native-udp';

const crypto = require('crypto');
const dgram = require('react-native-udp');

//const coap = require('coap');

const socket = dgram.createSocket('udp4')

const DeviceOneMapScreen = () => {
  const navigation = useNavigation();

  const socket = dgram.createSocket('udp4')

//end of code

## Current behavior
error:

null is not an object (evaluation 'Sockets.createSocket')

**Comment by Kyu** [comment]
related to #206
