### ISSUE TITLE
Android - UdpSocketsModule method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by codeion** [tradle/react-native-udp#230]
## Description
/node_modules/react-native-udp/android/src/main/java/com/tradle/react/UdpSocketsModule.java:33
error: method does not override or implement a method from a supertype

## Steps to reproduce
1. Run build in Android Studio

Invalid interface method override:
```js
@Override
public List<Class<? extends JavaScriptModule>> createJSModules() {
    return Collections.emptyList();
}
```

## Current behavior
Gradle build failing.

## Expected behavior
Gradle build passing.

**Screenshots**
<img width="1432" alt="Screenshot 2022-12-07 at 7 37 46" src="https://user-images.githubusercontent.com/7738355/206018309-8ff89c6f-1df2-40a6-b102-848dbe931093.png">

## Relevant information
|             |     |
| ----------- | --- |
| OS | any   |
| react-native | 0.70.6   |
| react-native-udp  | 4.1.6   |

**Comment by congnt148** [comment]
facing same issue :(((

**Comment by marcoazn89** [comment]
Was forced to lock version 4.1.5 for now

**Comment by szbenceg** [comment]
I had the same problem. With version 4.1.5  everything works fine.

**Comment by mihailpozarski** [comment]
I'm having the same issue as described here

**Comment by ShalomGH** [comment]
I have the same problem
