### ISSUE TITLE
error: method does not override or implement a method from a supertype @Override

### ISSUE THREAD

**Issue by pablolucas890** [tradle/react-native-udp#231]
## Description
```
/home/pablo/Documentos/Controllar/AppControllar/mobile-app-fork/node_modules/react-native-udp/android/src/main/java/com/tradle/react/UdpSocketsModule.java:33: error: method does not override or implement a method from a supertype
    @Override
```

## Steps to reproduce
1. Install react-native-udp
2. build apk with react native cli
3. gradle plugin version `4.2.2`
4. gradle version `6.7.1`

Or code:
```js
    //@Override // I remove this @Override and build work
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
```

## Current behavior
I was trying use the react-native-udp to send a payload to broadcast and after instalation when i"m building the app with `react-native run android`, the gradle return this error:

## Expected behavior

**Screenshots**
![image](https://user-images.githubusercontent.com/56566628/206182202-77ebdc67-7cca-4af3-a821-2fff5a98722f.png)

## Relevant information
|             |     |
| ----------- | --- |
| OS | linux   |
| react-native | 0.63.1   |
| gradle | 6.7.1   |
| gradle plugin  | 4.2.2   |
| react-native-udp  | 4.1.6   |

## Fixing the error

To fix error for moment, I remove the `@Override` on List and the build work, but I don't understand why this error

**Comment by congnt148** [comment]
facing same issue :(((

**Comment by pablolucas890** [comment]
You try comment the `@Override`?

**Comment by aaronzalez200** [comment]
I comment the @Override at line 33 as well and it solved my issue.

**Comment by sperezm97** [comment]
👁️

**Comment by bitcrumb** [comment]
There is no `createJsModule` method in ReactPackage class, see: https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/java/com/facebook/react/ReactPackage.java

Not sure how this slipped through?

**Comment by bitcrumb** [comment]
Seems like this `createJsModule` was once present (looong ago, 2017) and removed:

See: https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8#diff-f99c473bd9fffd77d50d0a7cc9224c1f9b216ef1edfc7b5aad3be0c12da7d378

**Comment by bitcrumb** [comment]
Here's a patch where I just removed the method (based on my observations above).

You can use this patch with `https://www.npmjs.com/package/patch-package`, which is truly a recommended library for managing patches on node_modules libraries for your app (we currently manage multiple patches this way outselves).

[react-native-udp+4.1.6.patch](https://github.com/tradle/react-native-udp/files/10258006/react-native-udp%2B4.1.6.patch)

**Comment by pablolucas890** [comment]
Good patch

**Comment by pablolucas890** [comment]
I'll close this issue for moment, the patch fix bug for me
