### ISSUE TITLE
It is not working properly in new version of react native

### ISSUE THREAD

**Issue by dev-aniketj** [tradle/react-native-udp#245]

**Comment by FredyVia** [comment]
same too

**Comment by anthonymittz** [comment]
Not sure if it's relevant to your particular problem, but in case it would help: did you run the `npm run android` script after installing the package with npm?

For me, it's working just fine with the `react-native@0.71.6`.
The only problem I've encountered was the "`Sockets.createSocket()` method is null". Usually during the development process, I run the Metro server and connect to it remotely from an Android device. This was the case this time. The catch is that `react-native-udp` package requires some code to be compiled on the native side, the Metro was missing this code, thus the missing method. The `npm run android` did all the necessary linking/compilations and resolved the issue.

**Comment by nanokes** [comment]
I am having this same issue, I tried manually linking too, but it didn't work. Did anyone find a solution?

**Comment by Productivix** [comment]
I just tested this morning with last RN V 0.71.10 and it works

**Comment by falakjatin** [comment]
> I just tested this morning with last RN V 0.71.10 and it works

I am currently using and here are the details

"react": "18.2.0",
"react-native": "0.72.4",
"react-native-udp": "^4.1.7"

Basically I am trying to create a tictactoe which can be played on different devices (if on same network)

![image](https://github.com/tradle/react-native-udp/assets/60683893/8df544f7-3af3-4783-82fd-4e1947240e71)

Here are the logs on metro

 LOG  Running "tictactoe" with {"rootTag":251,"initialProps":{}}
 ERROR  Invariant Violation: "tictactoe" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

```
const socket = UdpSocket.createSocket({ type: 'udp4' });

useEffect(() => {
  socket.on('message', (data, rinfo) => {
    setMessage(data.toString())
    socket.send('Hello from the server!', undefined, undefined, rinfo?.port, rinfo?.address, (error) => {
      if (error) {
        console.log('Error sending message:', error);
      } else {
        console.log('Message sent successfully');
      }
    });
    console.log('Message received:', data.toString());
  });

  socket.on('listening', () => {
    console.log('Server listening on port:', socket.address().port);
    setConnectionStatus(`Server listening on port ${socket.address().port}`);
  });

  socket.bind(8888);

  return () => {
    socket.close();
  };
}, [isServer]) // isServer is just a boolean controlled by a button

  const sendMessage = () => {
    if (isServer) return;

    socket.send('Hello from the client!', undefined, undefined, 8888, ipServer, (error) => {
      if (error) {
        console.log('Error sending message:', error);
      } else {
        console.log('Message sent successfully');
      }
    });
    socket.on('message', async (message, remoteInfo) => {
      setMessage(message.toString())
    });
  };
```

**Comment by Productivix** [comment]
hi, 
your : const socket = UdpSocket.createSocket({ type: 'udp4' });
 is not **inside** the useEffect : , you should write instead : 
```

useEffect(() => {
    const fetchIpAddress = async () => {
      const ip = await NetworkInfo.getIPV4Address();
      setIpAddress(ip);
    };

    fetchIpAddress();
    if (isServer) {
      // Configura la aplicación como servidor
      const server = UdpSocket.createSocket('udp4');

      server.on('message', (data, rinfo) => {....

```

**Comment by falakjatin** [comment]
Sorry guys for replying little late to solve above error I simply run command: cd ios && pod install (this fixed my problem)

Thanks for the comments.

**Comment by dkornilove** [comment]
stil an issue on android rn 0.74.1, no idea how to fix

**Comment by sauryagur** [comment]
Still an issue with react-native@0.81.5

**Comment by gibo77** [comment]
Hello UDP Fanatics,I just upgraded to latest React Native feW weeks ago. Worked well in Android. Actually improved. Haven’t tried yet in iOS. See attached and you can download in Android. 





Sent from Yahoo Mail for iPhone


On Monday, November 10, 2025, 4:58 AM, Saurya Gur ***@***.***> wrote:

sauryagur left a comment (tradle/react-native-udp#245)
Still an issue with ***@***.***
