### ISSUE TITLE
can we share file or document via udp?

### ISSUE THREAD

**Issue by Shivani12345** [tradle/react-native-udp#251]
I want to send and receive files,documents like pdf or images with server client connection. can we achieve this with UDP?
Currently I have tried this with file convert in to base64 string and pass as message and another side can receive it too.but its not proper way when document size is large. can you please help?

**Comment by gibo77** [comment]
My opinion UDP is only for light weight sending of data. You may have to use TCP. 


Sent from Yahoo Mail for iPhone


On Wednesday, September 6, 2023, 3:31 AM, Shivani12345 ***@***.***> wrote:




I want to send and receive files,documents like pdf or images with server client connection. can we achieve this with UDP?
Currently I have tried this with file convert in to base64 string and pass as message and another side can receive it too.but its not proper way when document size is large. can you please help?
