### ISSUE TITLE
android can not receive message

### ISSUE THREAD

**Issue by ly678910** [tradle/react-native-udp#254]
socket.on('message', function(msg, rinfo) {
  
      console.log('Message received', msg)

    })

No response message is received here

**Comment by ly678910** [comment]
Hi, author

 Can you tell me how to fix it？thanks

**Comment by gibo77** [comment]
My application worked. I will see my program later share here. You need to set the UDP server that sends back. You may expect asynchronous communication 


Sent from Yahoo Mail for iPhone


On Wednesday, May 8, 2024, 10:40 AM, ly678910 ***@***.***> wrote:




Hi, author

Can you tell me how to fix it？thanks

**Comment by ly678910** [comment]
ok ，thanks, I will try

**Comment by ly678910** [comment]
Problem solved
