### ISSUE TITLE
Multicast

### ISSUE THREAD

**Issue by jmc420** [tradle/react-native-udp#29]
Hi

I have added the code that implements addMembership and dropMembership in this fork:

https://github.com/jmc420/react-native-udp

Do you want me to create a pull request into this repository? I am not an Objective C developer so you might want to compare the fork.

I have tested the changes and they appear to work.

James

**Comment by mvayngrib** [comment]
@jmc420 thanks for the PR. May I ask how you tested it? 
@aprock these methods adhere to the dgram spec, where they are synchronous. So they don't have callbacks to report to the JS side on whether the invocation was successful or not. Do you have any suggestions on how to handle errors? Maybe provide an optional callback param or emit an event for that socket?

**Comment by aprock** [comment]
An optional callback seems the right approach.  It has the least impact on existing integration.

**Comment by mvayngrib** [comment]
@jmc420 up for adding some callbacks?

**Comment by jmc420** [comment]
The NodeJS API does not support error handling. There is no return value or callback and it does not say that it raises an "on" event if there is a failure in the underlying joinGroup call: 

https://nodejs.org/api/dgram.html#dgram_socket_addmembership_multicastaddress_multicastinterface

I experimented with how NodeJS handles errors in the addMembership call.

Calling addMembership without binding the socket results in no "on" events or runtime exceptions - the socket just never receives any data. Calling addMembership twice after the socket is bound does not trigger an event in the "on" handler but causes a javascript run time error which has to be handled by a try catch block if you want to trap it. Rather than firing an "on" event or invoking a callback, I guess an error in the React native module should trigger a javascript runtime error (i.e. throw new Error). It does not look as though the React native bridge/modules support this though? 

In the react-native-udp java version, the exceptions generated by the call to addMembership on line 182 of UdpSockets.java are swallowed and logged to FLog. I guess the equivalent in the Objective C version is just to write to NSLog or maybe Facebook have an Objective C equivalent of FLog? Maybe just leave the Objective C version to do the same as the Java version - i.e. just log the error?

**Comment by aprock** [comment]
for ios logging use RCTLog.

Yes, unfortunately node.js' synchronous api's have this issue.  We should continue logging it, and extend the api with a callback on both platforms.

@jmc420 I can add it to the android implementation, if you want to take the ios one.

**Comment by jmc420** [comment]
I am not sure about this because changing the signature of the NodeJS
addMembership function will cause the typescript compiler to generate an
error. Just logging the error and generating an exception when FB makes
this possible sounds better.

**Comment by aprock** [comment]
@jmc420 agreed (see my earlier edit).  this fix needs to be in for both addMembership and dropMembership.

**Comment by JasonMore** [comment]
@aprock @jmc420 I have a use case for this, looking forward to seeing the merged PR. If there is someway I can help, I'd be happy to try. I've not done any objective-c before :-D

**Comment by jmc420** [comment]
Hi Jason

Perhaps try out the existing patch to see if it works for you? I am not an Objective C programmer so it is just a bodge.

After you have tried it, perhaps it can be merged as is until someone who is an Objective C programmer wants to do something with it.

**Comment by JasonMore** [comment]
@jmc420 your fork is working for me, many thanks. Not sure about the error discussion above though.

**Comment by aprock** [comment]
merged, since this adds parity with the android implementation. the exceptions will be added later.
available in 1.2.9
