### ISSUE TITLE
Crash when run project

### ISSUE THREAD

**Issue by yesmeck** [tradle/react-native-udp#3]
I create a new project follow the readme, but after added react-native-udp, the project crashes every time I run it. I'm using Xcode 6.4 and react-native 0.7.1

**Comment by mvayngrib** [comment]
could you publish your project to github and I'll check it out?

**Comment by yesmeck** [comment]
https://github.com/yesmeck/AwesomeProject

**Comment by mvayngrib** [comment]
cool, thx, seems it's todo with https://github.com/tradle/react-native-udp/pull/2 , will pull that now

**Comment by mvayngrib** [comment]
merged #2 and republished as 0.0.11, your project no longer crashes for me

**Comment by yesmeck** [comment]
Thanks.
