### ISSUE TITLE
cannot send to 255.255.255.255

### ISSUE THREAD

**Issue by roycclu** [tradle/react-native-udp#31]
dgram works fine with all known addresses in my network, except 255.255.255.255 
When set to 255.255.255.255 the socket command for send is not called

dgram.createSocket("udp4").send(.., 255.255.255.255, .) 

Am I missing something here? Is react-native-udp not designed to work with broadcast?

**Comment by h124551753** [comment]
I also have this problem for ios

**Comment by h124551753** [comment]
if solved this problem with set 'socket.setBroadcast(true) ' in callback function of socket.bind.

this.socket.bind(UDP_LISTEN_PORT, (err)=>{
      if (err) throw err;
      this.socket.setBroadcast(true);
    });

**Comment by roycclu** [comment]
thanks man!! really helpful.

**Comment by pablolucas890** [comment]
Thank you my friend, u help me
