### ISSUE TITLE
question - IP address discrepancy

### ISSUE THREAD

**Issue by ORESoftware** [tradle/react-native-udp#34]
This module works when my machine (laptop) is on this IP address

`10.0.0.24`

but sometimes my machine switches to this IP address:

`10.235.101.163`

and then this module stops working

any idea why that might be?

**Comment by mvayngrib** [comment]
@ORESoftware not sure, and it's a bit out of scope for this module :)

**Comment by ORESoftware** [comment]
My guess was I was switching between wifi networks at home. One was a "private" router in my apt. The other was a "public" xfinity router. I think the xfinity router blocks communication between devices on the network. AKA my android phone could not comm with my laptop despite being on the same intranet/subnet.
