### ISSUE TITLE
Duplicate interface definition for class 'RCTBridge' with react > 4.0

### ISSUE THREAD

**Issue by lcwangchao** [tradle/react-native-udp#35]
see react native 4.0 break changes: https://github.com/facebook/react-native/releases/tag/v0.40.0

**Comment by tohjg** [comment]
i have create a pull request #36. please review.

**Comment by mvayngrib** [comment]
@tohjg thanks for the PR! I won't have time to review until > Feb 12th. Happy to review then if someone else doesn't do it before me! This will need to be a semver major release

**Comment by tohjg** [comment]
@mvayngrib you are welcome, bro. looking forward for this PR released to npm registry soon.

**Comment by pauliusuza** [comment]
LGTM. Reviewed and tested on react native 40+

**Comment by cchance27** [comment]
is this why i can't get udpsocket to work on my new project/latest react-native? lol

**Comment by mvayngrib** [comment]
hey guys, @tohjg 's PR has been merged and released as 2.0.0

**Comment by tohjg** [comment]
NPM registry updated! Thanks
