### ISSUE TITLE
undefined is not an object (evaluating 'Sockets.createSocket')

### ISSUE THREAD

**Issue by cchance27** [tradle/react-native-udp#37]
I think i have react-native-udp installed properly, but whenever i try to instantiate snmp-native which uses dgram, i'm getting an error "Cannot read property 'createSocket' of undefined"

The thing is this same exact code works in node, so its definitely something related react-native, but i'm to new or too stupid to figure out what the hell is the cause of it.

Anyone get snmp-native working with react-native-udp, or know of anything in react-native-udp that could be causing this, or does an error like this mean somehow i screwed up the react-native-udp install?

**Comment by cchance27** [comment]
I've been struggling with it and the error i'm getting now is undefined is not an object evaluating sockets.create

**Comment by jesper-johansson** [comment]
If anyone else has this problem try rebuilding and restarting the simulator
