### ISSUE TITLE
incompatability with snmp-native?

### ISSUE THREAD

**Issue by cchance27** [tradle/react-native-udp#38]
not sure whats going on when i use react-native-udp to get snmp-native working, i'm getting an odd error "JSON value '{ exclusive = 1; port = 0}' of type NSDictionary cannot be converted to NSNumber

`function Session(options) {
    var self = this;
    self.options = options || {};
    defaults(self.options, exports.defaultOptions);
    self.reqs = {};
    self.socket = dgram.createSocket(self.options.family);
    self.socket.on('message', msgReceived.bind(self));
    self.socket.on('close', function () {self.socket = undefined; });
    self.socket.bind({
        port: 0, 
        exclusive: true 
    });
}`

i'm calling it with just a var sess = new snmp.Session(conn) and that throws the red screen so its definitly something with that bind.

Since dgram is now being replaced via the shim, to be react-native-udp, i don't get why calling self.socket.bind is throwing that red screen error and i'm pulling my hair out trying to figure it out, i'm new to RN so i'm pretty sure its either a bug with R-N-UDP or my code and i'm not sure who to ask. Since the code works on standard dgram in a nodejs app i figured i'd ask here

**Comment by mvayngrib** [comment]
@cchance27 if you take a look at the bind method, https://github.com/tradle/react-native-udp/blob/master/UdpSocket.js#L74 , it doesn't support passing in an options object. I understand the native dgram api does, so if you want to submit a PR, please do :)

**Comment by cchance27** [comment]
Well crap ya i see that now, but holy hell is doing that PR over my head skill wise :(

**Comment by mvayngrib** [comment]
closing in favor of #80
