### ISSUE TITLE
react native 0.40 RCTBridge.h and RCTLog.h error compile

### ISSUE THREAD

**Issue by mauriciocoelho** [tradle/react-native-udp#40]
Hello, 
I was with a problem to link lib in my project with react-native@0.40

I fix it changing import format `#import "RCTLog.h"` to  `#import <React/RCTLog.h>` and `#import "RCTBridge.h"` to `#import <React/RCTBridge.h>`

**Comment by mvayngrib** [comment]
@mauriciocoelho version 2.0.0 already has this fix :)

**Comment by mauriciocoelho** [comment]
@mvayngrib nice! Now I saw in the code, but not is not in npm yet.
Thanks
