### ISSUE TITLE
iOS native headers moved

### ISSUE THREAD

**Issue by dpxcc** [tradle/react-native-udp#42]
iOS native headers have been moved in React Native 0.40.0. Please update here and npm.

[https://github.com/facebook/react-native/releases/tag/v0.40.0](https://github.com/facebook/react-native/releases/tag/v0.40.0)

**Comment by mvayngrib** [comment]
already released in 2.0.0

**Comment by dpxcc** [comment]
Can you also update rn-nodeify? It's currently using 1.2.0
