### ISSUE TITLE
message recieved after 2-3 seconds delay

### ISSUE THREAD

**Issue by mozi22** [tradle/react-native-udp#47]
Hi, 

Thanks for the awesome library. I am trying to use it in an application where I will be recieving a message each 50ms. Right now when I send a single packet, I recieve it after a 2-3 seconds delay. Is it the normal expected behavior ? If not, can I do something to make it faster ?

I am debugging it on an **Google Nexus 9 tablet**.

I am recieving a CANMessage using the [busMaster software.](https://www.etas.com/en/products/applications_busmaster.php)

**Comment by cristovao-trevisan** [comment]
Hello, I was having the same error because hostname could not be resolved (blocking the receiving thread), as I have no DNS in my network (I'm using an IOT device, ESP8266, in AP mode). If you also don't have a DNS this should fix your problem

**Comment by cstranex** [comment]
I was having the same problem where my socket would freeze every so often for a couple seconds. So far it appears using @cristovao-trevisan's suggestion fixes the problem
