### ISSUE TITLE
Not receiving broadcast messages on Android

### ISSUE THREAD

**Issue by fabiopelosin** [tradle/react-native-udp#50]
Thank you for the great lib, very handy.

I’m observing a behaviour whereby broadcast messages are not received on Android (the same code works fine on iOS).

After a quick research I found some reports that indicate that it is necessary to acquire a MulticastLock in order to listen for broadcast messages. I attempted to implement the patch but my attempts did not manage to receive broadcast messages.

Any suggestion in this regard?

### References:

- https://stackoverflow.com/a/43549938
- https://stackoverflow.com/a/22304267
- https://pzoleeblogen.wordpress.com/2014/03/04/android-udp-broadcast-message-is-not-received/
- http://discourse.libcinder.org/t/new-osc-block-on-android-receiver-does-not-get-any-messages/335/9

**Comment by crearc** [comment]
@fabiopelosin were you able to figure this one out? I'm also running into this on Android.

**Comment by crearc** [comment]
It seems like the package is already attempting to acquire the lock: https://github.com/tradle/react-native-udp/blob/master/android/src/main/java/com/tradle/react/UdpSockets.java#L173

The code seems accurate to acquire the lock on Android, so it might be a different issue?

**Comment by fabiopelosin** [comment]
@crearc unfortunately not. The lock that your are referencing if I recall correctly is for multicasting. Yet I tried a similar strategy for broadcasting and it doesn't work. Also to my eyes the permissions look good.

**Comment by crearc** [comment]
Oh I gotcha. I was confusing multicasting vs. broadcasting (newish to networking stuff). I'm actually not receiving any multicast messages at all! Nothing is coming through :(. I am able to send on Android, just not receive. Not doing any iOS atm.

Here's my (slightly truncated) code:
```
export const multicastIP = '239.1.1.1'
export const multicastPort = 7123

startUdpClient() {
    var socket = dgram.createSocket('udp4')
    
    socket.bind(multicastPort)

    socket.on('listening', (err) => {
      if (err) throw err

      socket.setBroadcast(true)
      socket.addMembership(multicastIP)

      var buf = toByteArray('g,F')

      socket.send(buf, 0, buf.length, multicastPort, multicastIP, function(err) {
        if (err) throw err
        console.log('udp message was sent')
      })
    })

    socket.on('message', (data, rinfo) => {
      console.log('udp message was received: ', data, JSON.stringify(rinfo))
    })
  }
```

**Comment by aprock** [comment]
anything useful in the logcat?

**Comment by crearc** [comment]
Message is sent. It actually receives it's own message (last line), but doesn't get others.

```
I/ReactNativeJS(13084): 'socket-0', 'binding, address:', '0.0.0.0', 'port:', 7123
I/ReactNativeJS(13084): 'socket-0', 'bound to address:', '0.0.0.0', 'port:', 7123
I/ReactNativeJS(13084): { '0': 103, '1': 44, '2': 70, '3': 49, '4': 0 }, 5, 7123, '239.1.1.1'
I/ReactNativeJS(13084): udp message was sent
I/ReactNativeJS(13084): 'udp message was received: ', { '0': 103, '1': 44, '2': 70, '3': 49, '4': 0 }, '{"address":"192.168.1.2","port":7123,"family":"IPv4","size":5}'
```

**Comment by crearc** [comment]
Wow, so apparently it's a hardware-specific issue. My Kindle Fire receives the messages, but not the Samsung Galaxy Tab A 7...

**Comment by crearc** [comment]
The plot thickens... So I switched to a different router. The Samsung works for send/recv, as does the Fire. The Nexus still does not send or recv... What settings on the router would cause this to occur?

**Comment by fabiopelosin** [comment]
For the record I discovered the issue on a Nexus 5.

I have no clue about how the router might interfere with some devices but not with others.

**Comment by ASVBPREAUBV** [comment]
Did someone take a look at the native Implementation of socket.addMembership(multicastIP) function?

**Comment by asukiaaa** [comment]
In my case, I cannot send (and maybe also receive) udp signal from Android.
After creating MulticastLock in Java code, I succeeded in sending and receiving.
```java
import android.net.wifi.WifiManager;
import android.net.wifi.WifiManager.MulticastLock;

WifiManager wifi = (WifiManager) context.getSystemService(Context.WIFI_SERVICE);
MulticastLock lock = wifi.createMulticastLock("lock");
lock.acquire();
```

I release lock after that.
```java
lock.release();
```

Thank you.

References:
https://qiita.com/niusounds/items/f080537417a0512acf15
https://pzoleeblogen.wordpress.com/2014/03/04/android-udp-broadcast-message-is-not-received/

**Comment by mvayngrib** [comment]
@thierryfornetti i'm not that familiar with the java half of this module, maybe @aprock knows

**Comment by BaQaDa** [comment]
> nightmare

Seriously it is, I am struggeling with the same stuff , some devices send and receive; other devices do not.
Moreover , sometimes on the same device it receive and other times not... What is going on !!??

**Comment by imeijie** [comment]
[Many devices have multicast disabled in the kernel [36966360] - Visible to Public - Issue Tracker](https://issuetracker.google.com/issues/36966360)

**Comment by akshay20jha** [comment]
I am facing a similar issue unable to get data from multicast url unable to get data from example.local its really getting difficult for me to resolve the issue
