### ISSUE TITLE
error: package com.tradle.react does not exist???

### ISSUE THREAD

**Issue by paranat9221** [tradle/react-native-udp#58]
hi, I use react-native-udp for getting ntp time but I got this errors. 

```
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
C:\Users\Computer\...\MainApplication.java:6: error: package com.tradle.react does not exist
import com.tradle.react.UdpSocketsModule;
                       ^
C:\Users\Computer\...\MainApplication.java:41: error: cannot find symbol
          new UdpSocketsModule(),
              ^
  symbol: class UdpSocketsModule
Note: C:\Users\Computer\...\MainApplication.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
:app:compileDebugJavaWithJavac FAILED
```

Can someone help me fix this problem??

thank you :)

**Comment by mvayngrib** [comment]
maybe you forgot to run `react-native link`?

**Comment by paranat9221** [comment]
@mvayngrib yes I already try it both `react-native link ` and react-native link react-native-udp but its still doesn't work ;(

**Comment by mvayngrib** [comment]
@paranat9221 you're using `react-native run-android` to run your project?

**Comment by paranat9221** [comment]
@mvayngrib yes

**Comment by mvayngrib** [comment]
@paranat9221 are you able to successfully use other react-native modules with android components?

**Comment by paranat9221** [comment]
@mvayngrib yeah, I already use others component such as splashscreen ,FacebookSdk ,PushNotification and it's work fine

**Comment by mvayngrib** [comment]
@paranat9221 sorry, not sure how i can help. If you haven't already, make sure:

1. you can find UdpSocketsModule.java in node_modules
2.  `compile project(':react-native-udp')` is in the android/app/build.gradle dependencies block
3. these two lines are in android/settings.gradle:
```
include ':react-native-udp'
project(':react-native-udp').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-udp/android')
```
4. just in case, clean before u run again: `cd android && ./gradlew clean` then `react-native run-android` again

**Comment by paranat9221** [comment]
@mvayngrib it's work now! that is my fault. I forget to add `compile project(':react-native-udp')` in build.gradle.

thank for your support :)

**Comment by mvayngrib** [comment]
@paranat9221 cool :)
