### ISSUE TITLE
Index out of bound error iOS

### ISSUE THREAD

**Issue by nim23** [tradle/react-native-udp#62]
I am currently seeing the below index out of bound issue when calling `client.bind(0)` which crashes our app, and really have no clue why it's happening.

<img width="1395" alt="screen shot 2017-12-01 at 11 10 42" src="https://user-images.githubusercontent.com/1999331/33480391-a026f2ee-d688-11e7-92ea-bb94b6081f01.png">

Looking at https://github.com/tradle/react-native-udp/blob/master/UdpSocket.js#L99 and the exported method here https://github.com/tradle/react-native-udp/blob/master/ios/UdpSockets.m#L53 everything seems to be in order but somehow we seem to be missing an argument when we call `client.bind(0)`. Has anyone else faced the issue?

**Comment by mvayngrib** [comment]
whoever finds a stable reproduction of this, please reopen! Closing for now
