### ISSUE TITLE
Support for RFC-1123 hostnames (e.g. 0.pool.ntp.org)

### ISSUE THREAD

**Issue by steadicat** [tradle/react-native-udp#63]
The [valid host name regex](https://github.com/tradle/react-native-udp/blob/master/UdpSocket.js#L26) references [RFC-952](https://tools.ietf.org/html/rfc952), which disallows hostnames that start with numbers, such as `0.pool.ntp.org`.

RFC-952 was superseded by [RFC-1123](https://www.ietf.org/rfc/rfc1123.txt) around 28 years ago. RFC-1123 reads:

> The syntax of a legal Internet host name was specified in RFC-952 [DNS:4].  One aspect of host name syntax is hereby changed: the restriction on the first character is relaxed to allow either a letter or a digit.  Host software MUST support this more liberal syntax.

I think it’s time to update that regex. 😉

**Comment by glenne** [comment]
I've added a pull request to fix this:  https://github.com/tradle/react-native-udp/pull/77.  In case someone needs this, the proper regex is available at https://www.regextester.com/23.

**Comment by mvayngrib** [comment]
fixed by #77
