### ISSUE TITLE
Example for sending without listening?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [tradle/react-native-udp#65]
I have a remote service which is listening for UDP packets at a specific host/port.

Is there an example of how I would, from react-native, bind a socket to send to that host/port? The examples all seem based on listening (server) but I want to send without any listening (client).

**Comment by mvayngrib** [comment]
@GeoffreyPlitt the example shows how to send: https://github.com/tradle/react-native-udp/blob/master/examples/rctsockets/index.ios.js#L76. I don't remember whether I ever tried it without listening. Does it not work for you?

**Comment by GeoffreyPlitt** [comment]
Gotcha, will try that!
