### ISSUE TITLE
Can you make a lib of tcp ?

### ISSUE THREAD

**Issue by PatrickSCLin** [tradle/react-native-udp#7]
HI, is possible to make a the other lib of tcp ? like GCDAsyncSocket?

**Comment by mvayngrib** [comment]
definitely possible and shouldn't be too hard. I'll probably take a stab at it in the near future.

**Comment by PatrickSCLin** [comment]
thanks bro, I'm just new to React Native, 
it's awesome, but I can't use TCP socket from JS,
I found a component, WebSocket which in React Native, 
but it looks like only allow to using for http and ws.

**Comment by mvayngrib** [comment]
depending on your use case, you might be able to use react-native-udp with [utp](https://github.com/mafintosh/utp), or [rudp](https://github.com/shovon/node-rudp). But that's only if your code is running on both sides of the "tcp" connection, like if you're building a peer to peer app.

**Comment by PatrickSCLin** [comment]
Can I use utp in *.ios.js ?

**Comment by mvayngrib** [comment]
sure, .ios.js is just a naming convention, it's really just .js

**Comment by PatrickSCLin** [comment]
.io.js is running on iOS side right ? 

I thought utp only work on Node.JS ?

**Comment by PatrickSCLin** [comment]
my goal is building an app which able to access data via telnet (port 23 or ssh) protocol

would like to using tcp socket in .ios.js for some reasons

**Comment by mvayngrib** [comment]
React Native uses JavaScriptCore, so the JS environment is pretty similar to being in a browser. Modules like this one attempt to make it more like a node.js environment. tcp is on the todo list :)

**Comment by PatrickSCLin** [comment]
I just tried to make a lib "RCTTCPSocket" , it's able to connect now, 
https://github.com/PatrickSCLin/RCTTCPSocket
will try to implement return the received data as byte-array later, thanks for your help :)

**Comment by mvayngrib** [comment]
cool! I will be keeping an eye on it :)
