### ISSUE TITLE
Bound port not same as what my server is seeing

### ISSUE THREAD

**Issue by shashfrankenstien** [tradle/react-native-udp#73]
On the React-Native side, I'm binding to port 55555.

```js
import dgram from 'react-native-udp';
import { Buffer } from 'buffer'

const foo = ()=>{
	var socket = dgram.createSocket('udp4')
	socket.bind(55555, '0.0.0.0', (e)=>{
		if(e) console.log(e)
	})
	socket.once('listening', function() {
		var buf = Buffer.from(JSON.stringify('msg'))
		socket.send(buf, 0, buf.length, 5000, MACHINE_LOCAL_IP, function(err) {
		    if (err) alert(err)
		    console.log('Sent to', MACHINE_LOCAL_IP)
		})
	})
}
```

I'm seeing the following console log
```
socket-0 bound to address: 0.0.0.0 port: 55555
Sent to [...]
```

It works as expected maybe 8 / 10 times. On my server side, I'm opening a UDP socket using python

```py
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.settimeout(1)
sock.bind(('0.0.0.0', 5000))
while True:
	try:
		data, in_address = sock.recvfrom(1024)
		print(in_address)
	except socket.timeout:
		pass
	except Exception as e:
		print(e)
		break
```

When I run `foo` multiple times, here's my python output 

```
('192.168.0.5', 55555)
('192.168.0.5', 55555) 
('192.168.0.5', 55555)
('192.168.0.5', 55555)
('192.168.0.5', 55555)
('192.168.0.5', 55555)
('192.168.0.5', 52917)
('192.168.0.5', 49619)
('192.168.0.5', 63532)
('192.168.0.5', 55555)
('192.168.0.5', 55555)
```

I'm not able to figure out why the port is changing!

**Comment by mvayngrib** [comment]
@shashfrankenstien sorry, i won't have time to help in the near future! However, my first thought is: you're not printing the received message 'msg', so it might be another sender sending you msgs from those other ports. Maybe you can check

**Comment by shashfrankenstien** [comment]
@mvayngrib thank you for the quick response! The code I’ve posted is modified to just demonstrate the issue. It is much larger where I am logging each message. So the server is in fact receiving the message. I ran this shortened version using node dgram, and I don’t see this issue. That’s what led me to believe it has something to do with react-native-udp

**Comment by mvayngrib** [comment]
@shashfrankenstien ah, i see. Unfortunately, I don't have time to investigate this at the moment, but if you do figure out the issue, PRs are welcome :)

**Comment by shashfrankenstien** [comment]
Update: This doesn't seem to happen on Android!
