### ISSUE TITLE
Can't receive message when use muticast.

### ISSUE THREAD

**Issue by ldhios** [tradle/react-native-udp#74]
Hi,
   Thanks for your provide great lib.  I use in muticast. 

The bind function is normal , if not set the muticast address.
if the ip is set  muticast address.  Can't receive message.
  
    this.udpServer = dgram.createSocket('udp4');
    this.udpClient = dgram.createSocket('udp4');
    this.ip = '239.255.255.250'//if the ip is default 0,0,0,0;
    this.port = 7234;
    

    this.udpServer.bind(this.port,this.ip, (err) =>{
      if (err) throw err;

      that.updateChatter('this.udpServer bound to ' + JSON.stringify(this.udpServer.address()));

    })
    this.udpClient.once('listening', function() {
      this.udpServer.addMembership(this.ip);
    })
    this.udpServer.on('message', function(data, rinfo) {
      var str = String.fromCharCode.apply(null, new Uint8Array(data));
      that.updateChatter('this.udpServer received echo ' + str + ' ' + JSON.stringify(rinfo));

    })

send function 

```
  _sendMsg = (msg2) => {
    var msg = toByteArray(msg2)
      this.udpServer.send(msg, 0, msg.length, this.port, this.ip, function(err) {
        if (err) {
          that.updateChatter('this.udpServer sent data error' + JSON.stringify(error));
          throw err
        }
        

        that.updateChatter('this.udpServer sent data complete')
      })
    

  }
```

**Comment by mvayngrib** [comment]
@ldhios does this code work for you in Node.js?
