### ISSUE TITLE
Packet not sent until other packet received 

### ISSUE THREAD

**Issue by antonre999** [tradle/react-native-udp#81]
On Android my UDP broadcast packets aren’t getting sent until the device receives some other UDP packet.  If nothing on the network is sending packets then no packets ever leave my device. (Confirmed with wireshark).  Has anybody else seen this kind of behavior?

**Comment by shynst** [comment]
maybe this is related to my issue: #82?

**Comment by mvayngrib** [comment]
sorry guys, no time to help at the moment, but if you figure it out, PRs are welcome

**Comment by baharb** [comment]
This is my problem too. But when I use "send" in an interval, the app stops sending packets.

**Comment by baharb** [comment]
This problem exists in my application too. 
I'm using this library in a real-time application, and I have an interval that send and receive packet every 1000 msec. 
If packets can't receive, the application stop sending packets. 
and after a few minutes the app crashes and I see this error in log tab:
java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@1b53ea0d rejected from java.util.concurrent.ThreadPoolExecutor@718cdc2[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 934]
