### ISSUE TITLE
undefined is not an object (evaluating 'Sockets.createSocket')

### ISSUE THREAD

**Issue by Dimaspro100** [tradle/react-native-udp#86]
Hi
I got this error on IOS when starting up screen where  RNU  is located

react-native-cli: 2.0.1
react-native: 0.57.8

RNU is already linked :
  pod 'react-native-udp', :path => '../node_modules/react-native-udp'

Can anyone help me?)

**Comment by mvayngrib** [comment]
@Dimaspro100 did you follow the installation instructions in the readme? Are you also using Cocoapods?

**Comment by Dimaspro100** [comment]
Yes, I did.
Yes, we are using Cocoapods

**Comment by mvayngrib** [comment]
@Dimaspro100 in Xcode, under Build Phases, Link Binary with Libraries, do you see libUdpSockets.a?

**Comment by stephenmarkham** [comment]
I seem to be seeing the same issue, and no I do not see 'libUdpSockets.a' in the link binary with libraries section (nor can I find it to add).

**Comment by mvayngrib** [comment]
@stephenmarkham react-native version?

**Comment by stephenmarkham** [comment]
> @stephenmarkham react-native version?

    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-udp": "^2.6.1"

**Comment by mvayngrib** [comment]
@stephenmarkham react-native 0.60 changed how native modules are linked. I'll try to investigate this soon, but for now, you can try react-native 0.59

**Comment by stephenmarkham** [comment]
> @stephenmarkham react-native 0.60 changed how native modules are linked. I'll try to investigate this soon, but for now, you can try react-native 0.59

Thanks, will try that. It's caused a few errors initially so I will get back to you later on with the result

**Comment by stephenmarkham** [comment]
> @stephenmarkham react-native 0.60 changed how native modules are linked. I'll try to investigate this soon, but for now, you can try react-native 0.59

I can confirm that using version 0.59 solved my problem, thanks.

**Comment by lishanxin** [comment]
i have the same problem, on react-native 0.59.5. it occur on iphone, but android is worked well. Could you solved my problem?Thanks.

**Comment by lishanxin** [comment]
I have solved this problem. You can try it.
1:  npm install --save react-native-udp
2: open xcode for your project
3: Click "Show the Project Navigator" on the left window in xcode
4: Right Click the Group of "Libraries" 
5: Select 'Add Files to "your project name"'
6: find the path of react-native-udp, click the directory 'ios'
7: select file "UdpSockets.xcodeproj",and click "ADD". then you can find it present in Libraries.
8: on the mid window, select your TARGET ->  "General" -> scroll to "Linked Frameworks and Libraries" -> click the "plus" icon - select "libUdpSocket.a"
9：enjoy yourself！

**Comment by mvayngrib** [comment]
@lishanxin thanks! see the official docs here btw: https://facebook.github.io/react-native/docs/linking-libraries-ios.html
