### ISSUE TITLE
Remove .git file from node package

### ISSUE THREAD

**Issue by SoulKa** [tradle/react-native-udp#87]
**Issue:** cannot use npm install after installing react-native-udp

**Output:**
> npm ERR! path /Users/louis/Documents/alphainsideapp/node_modules/react-native-udp
> npm ERR! code EISGIT
> npm ERR! git /Users/louis/Documents/alphainsideapp/node_modules/react-native-udp: Appears to be a git repo or submodule.
> npm ERR! git     /Users/louis/Documents/alphainsideapp/node_modules/react-native-udp
> npm ERR! git Refusing to remove it. Update manually,
> npm ERR! git or move it out of the way first.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/louis/.npm/_logs/2019-05-22T11_53_29_560Z-debug.log

**Reproduce:**

1. have an existing react native project
2. execute `npm install react-native-udp`
3. install any other node package

**Workaround:**

- delete /node_modules/react-native-udp/.git

or

- delete /node_modules
- execute `npm install` to install all packages simultaniously # #

**Comment by mvayngrib** [comment]
@SoulKa hm, I don't see `.git` folder in `node_modules/react-native-udp/` after `npm install`. I checked the archive served at "https://registry.yarnpkg.com/react-native-udp/-/react-native-udp-2.5.2.tgz#503ab4054c16c57f90807e2e7c4c0fb407372783" and I don't see it in there either.

**Comment by SoulKa** [comment]
@mvayngrib thanks for the fast reply! I used npm to install the package, not yarn. Do they use the same source for node packages? Or maybe it falls back to git clone for some reason.

I'm working on a Mac and the .git file appears after every clean install. The react-native-udp version I use is the current vesion "react-native-udp": "^2.6.0".

I will try to reproduce this weird behaviour on Winodws and Linux the next days to see if the reason is somehow my computer.

**Comment by SoulKa** [comment]
so I tried it again on Windows:
I executed `npm install --save react-native-udp` in an empty folder and got the .git folder:

drwxr-xr-x 1 Louis 197121    0 Mai 24 21:27 ./
drwxr-xr-x 1 Louis 197121    0 Mai 24 21:27 ../
drwxr-xr-x 1 Louis 197121    0 Mai 24 21:27 .git/
drwxr-xr-x 1 Louis 197121    0 Mai 24 21:27 android/
drwxr-xr-x 1 Louis 197121    0 Mai 24 21:27 ios/
-rw-r--r-- 1 Louis 197121 1074 Okt 26  1985 LICENSE
-rw-r--r-- 1 Louis 197121  495 Okt 26  1985 normalizeBindOptions.js
-rw-r--r-- 1 Louis 197121 1829 Mai 24 21:27 package.json
-rw-r--r-- 1 Louis 197121  608 Okt 26  1985 react-native-udp.podspec
-rw-r--r-- 1 Louis 197121 2549 Okt 26  1985 README.md
drwxr-xr-x 1 Louis 197121    0 Mai 24 21:27 test/
-rw-r--r-- 1 Louis 197121 7870 Okt 26  1985 UdpSocket.js
-rw-r--r-- 1 Louis 197121  259 Okt 26  1985 UdpSockets.js

**Comment by mvayngrib** [comment]
yea, strange, never seen this kind of behavior from npm install

**Comment by Sbphillips19** [comment]
I am facing the same issue, but I don't see a git folder inside?

node_modules/react-native-udp
npm ERR! code EISGIT
npm ERR! git /Users/../node_modules/react-native-udp: Appears to be a git repo or submodule.
npm ERR! git     /Users/../node_modules/react-native-udp
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

**Comment by mvayngrib** [comment]
published 2.6.1 with fix

**Comment by SoulKa** [comment]
@Sbphillips19 Are you using Windows or Linux/Mac? Since the **.git** folder starts with a dot, it is hidden. On Windows you can check "show hidden folders" on the file browser. On Mac or Linux just run `ls -a` in the root of the node package "react-native-udp".
