### ISSUE TITLE
React Native 60 support

### ISSUE THREAD

**Issue by filippoitaliano** [tradle/react-native-udp#89]
I open this issue for tracking the progress to support React Native 60. We really need this fix. Maybe I'll submit a PR but I'm not an Android expert and I'm struggling with deadlines right now. Can anyone help?

**Comment by mvayngrib** [comment]
i just tried 0.60 and it worked fine:

```sh
react-native init udpexample
cd udpexample
yarn add react-native-udp
cp ../react-native-udp-example/App.js . # see https://github.com/mvayngrib/react-native-udp-example
yarn react-native run-android
```

**Comment by filippoitaliano** [comment]
It probably was a jetifier issue in the first 0.60 days. Now it works fine. Thanks for the verification.
