### ISSUE TITLE
Xcodeproj header search path needs to be updated

### ISSUE THREAD

**Issue by indraastra** [tradle/react-native-udp#9]
Due to the .xcodeproj file being nested one directory deeper, its search path in Build Settings needs to be changed to:

"$(SRCROOT)/../../node_modules/react-native/React"

**Comment by indraastra** [comment]
Looks like this got fixed, closing.

**Comment by mvayngrib** [comment]
@indraastra sorry, haven't had the bandwidth to check this. Glad it works
