### ISSUE TITLE
undefined is not an object (evaluating 'Sockets.createSocket')

### ISSUE THREAD

**Issue by bpourani** [tradle/react-native-udp#90]
Hello 
I do these:

    git clone https://github.com/mvayngrib/react-native-udp-example 
    cd react-native-udp-example
    npm install
   
    ./node_modules/.bin/react-native run-android

but I get the error on android emulator
undefined is not an object (evaluating 'Sockets.createSocket')

I linked all libraries 
what is my problem?

**Comment by mvayngrib** [comment]
i just updated react-native-udp-example to React Native 0.59.8, please try again:

```sh
git pull
yarn
./node_modules/.bin/react-native run-android
```

**Comment by bpourani** [comment]
now it gives me a new below error

FAILURE: Build failed with an exception.

* What went wrong:
Could not dispatch a message to the daemon.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by mvayngrib** [comment]
@bpourani that error doesn't sound specific to this module or that project, have you already googled it?

**Comment by bpourani** [comment]
it fix but a new error comes and it's about the module

 bundling failed: Error: Cannot find module 'babel-preset-react-native' from '/home/XX-XXX/Documents/react-native-udp-example'
- If you want to resolve "react-native", use "module:react-native"
    at Function.module.exports [as sync] (/home/XXX/Documents/react-native-udp-example/node_modules/resolve/lib/sync.js:71:15)

**Comment by mvayngrib** [comment]
@bpourani u probably need to restart the packager (the terminal where you ran `yarn start`)

**Comment by bpourani** [comment]
yarn start does not installed. I ran with react-native start and when I ran it, it gives me that error 

bundling failed: Error: Cannot find module 'babel-preset-react-native' from '/home/XX-XXX/Documents/react-native-udp-example'

**Comment by bpourani** [comment]
It gives me this error what is problem?

error: bundling failed: TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo

**Comment by mykhaliuk** [comment]
Got the same issue:
Created`react-native init myApp —template typescript` 
Added `cd myApp && yarn add react-native-dup`
Linked `react-native link react-native-udp`
Then 
```
import dgram from ‘react-native-udp’;

export const App = (props) => {
    const socket = dgram.createSocket(‘udp4’);
return null;
}
Got `undefined is not an object (evaluating 'Sockets.createSocket')`

**Comment by mvayngrib** [comment]
@mykhaliuk did you check that the library was actually linked? See here: https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking , you might need to link manually

**Comment by mykhaliuk** [comment]
Thanks, @mvayngrib! I've checked and it wasn't :/
Nevertheless, I did not succeed to link it manually also. Can't avoid the error about unable to find the header file
Are you planning to support auto-link in the future?

**Comment by mvayngrib** [comment]
@mykhaliuk auto-linking already works (if you're using RN >=0.60), u just need to `cd ios && pod install`, then run again from Xcode

**Comment by bpourani** [comment]
now my problem is how to set port and host to the specific port and host?

**Comment by bpourani** [comment]
Some one help me for it!!

![Screenshot from 2019-08-21 12-11-59](https://user-images.githubusercontent.com/17301738/63452838-e6a90900-c40c-11e9-9773-6527134f2f2f.png)

**Comment by mykhaliuk** [comment]
Was playing around and found out that I can't make it work with `expo`. Tried on the ejected expo and on just created expo-bare template - no success. `pod`s installed. But at the same time, it works well with a `react-native run-ios` command. 
What is ~my~ the problem? Is it something special with `expo`?

**Comment by mvayngrib** [comment]
@mykhaliuk yes, see expo's explanation: https://docs.expo.io/versions/latest/expokit/eject/#what-is-this-for

**Comment by serayuzgur** [comment]
Hi, I got the iOS version of the same problem.
` TypeError: undefined is not a function (near '...socket.connect...')`
I can receive UDP data but this error occurs after sending from the same device or simulator.
Do you have any hack or workaround ?

**Comment by austinbaccus** [comment]
I'm still getting this error.  Nothing mentioned so far has worked. 
This isn't for iOS React Native though, I'm using React Native to make a UWP app. Maybe that's the issue?

**Comment by MaheshVenkateshwaran1203** [comment]
Am trying this with expo. I get the error "TypeError: undefined is not a function, js engine: hermes"
Any clue on how to make this work? please :(
