### ISSUE TITLE
Can't connect to more than 3 ports (multiple sockets) on Android phone

### ISSUE THREAD

**Issue by miketall** [tradle/react-native-udp#91]
When I run the code, it works fine with trying connect to 3 sockets, but the code basically bricks when I try to do more than 3, causing me to do a hard restart.

I'm trying to do an IoT application where I have to connect to multiple sockets.

See attached code.  Thanks!

[react native udp IoT application test.txt](https://github.com/tradle/react-native-udp/files/3472473/react.native.udp.IoT.application.test.txt)

**Comment by mvayngrib** [comment]
@miketall thanks for the report! i'm afraid i won't have time to work on this in the short term, but if you figure out the cause, PRs are welcome!

**Comment by bpourani** [comment]
Hey Miketall

how did you run this code? could you send me your codes or project?

**Comment by bpourani** [comment]
did you do it on android emulator?

**Comment by cody-maheu** [comment]
`import React, { Component } from 'react';
import { Text } from 'react-native';

import dgram from 'react-native-udp';

class App extends Component {
	state = {
		msg: {}
	};

	async componentDidMount() {
		for (let i = 5000; i < 5002; i++) {
			let socket = await dgram.createSocket('udp4');

			await socket.bind(i, () => {
				console.log('binding');
			});

			await socket.on('error', err => {
				console.log(`server error:\n${err.stack}`);
				socket.close();
			});

			await socket.on('listening', () => {
				const address = socket.address();
				console.log(`server listening ${address.address}:${address.port}`);
			});

			await socket.on('message', function(msg, rinfo) {
				console.log(byteToString(msg));
			});
		}

		const byteToString = array => {
			var out, i, len, c;
			var char2, char3;

			out = '';
			len = array.length;
			i = 0;
			while (i < len) {
				c = array[i++];
				switch (c >> 4) {
					case 0:
					case 1:
					case 2:
					case 3:
					case 4:
					case 5:
					case 6:
					case 7:
						// 0xxxxxxx
						out += String.fromCharCode(c);
						break;
					case 12:
					case 13:
						// 110x xxxx   10xx xxxx
						char2 = array[i++];
						out += String.fromCharCode(((c & 0x1f) << 6) | (char2 & 0x3f));
						break;
					case 14:
						// 1110 xxxx  10xx xxxx  10xx xxxx
						char2 = array[i++];
						char3 = array[i++];
						out += String.fromCharCode(
							((c & 0x0f) << 12) | ((char2 & 0x3f) << 6) | ((char3 & 0x3f) << 0)
						);
						break;
				}
			}

			return out;
		};
	}

	render() {
		return <Text>Hello</Text>;
	}
}

export default App;`

**Comment by cody-maheu** [comment]
> Hey Miketall
> 
> how did you run this code? could you send me your codes or project?

I posted the code above, we ran it on both emulators and physical devices. We created a loop, you can expand the loop to listen to more ports. Each time we connected there was a cap at how many ports we could listen on. When we used a Galaxy s7 or the emulator, it was 3. When I used a google pixel it was 8. 

We ended up running very similar code using the react-native-tcp library. It works for up to 975 ports, we would prefer to use this library if we could get support for the same.

**Comment by cody-maheu** [comment]
Something worthy of noting is that when we ran the code, we found the cap for each device. When it is under the cap, it works fine and outputs everything. When it is over the cap, we get no response, even from the ports that were previously working. You can recreate this by looping > 3 or < 3. 

@bpourani

**Comment by bpourani** [comment]
Hey Miketall

thanks for helping me 
I want to connect this client to just one IP address and port. which part needs change?

**Comment by gibo77** [comment]
Hello Team!

It seems that I am having same issue here. When I get to socket-3, the App just crash. I have to restart the Samsung Tablet. Yes, I use Samsung tablet.
My code is below. This code is executed every time a button is pressed. I noticed every time I press the button socket-x will count where x=0 to 3. At three the App crashes. I did close the sockets, as you can see on my program.

`Send_UDP_Multicast = () => {
    let a = dgram.createSocket('udp4');
    let LocalPort = Math.random() * 60536 | 0 + 5000 // 60536-65536
    const RemotePort = 8266;

    a.bind(LocalPort,'192.168.1.3', (err) => { //Console: socket-x, binding to address: 0.0.0.0,
      if (err) { 
        a.close()
        console.log('Error binding local port.')
      }
        else console.log('Sucessful binding local port.')
    
    })

    a.on('message', (data, rinfo) => { //Console: socket-x, bound to address: 0.0.0.0, port: 65000 max
      console.log('Receiving remote data.')
      console.log(data)
      console.log(rinfo)
      a.close()
    })
    const msg = Buffer.from('Kitchen abc')
    a.send(msg, 0, msg.length, RemotePort, '224.0.1.3', (err) => {
      if (err) {
        a.close()
        console.log('Error sending UDP Multicast.')
      }  
      else console.log('Sucessful sending UDP Multicast.')
      
    //  this.updateChatter(' a sent data')
    })

    
  }`

**Comment by baharb** [comment]
> Hey Miketall
> 
> thanks for helping me
> I want to connect this client to just one IP address and port. which part needs change?

Hey guys @miketall , @bpourani 
Did you find any solution for this issue?
