### ISSUE TITLE
[iOS] Socket stop listening when the app coming from background (turned off the screen)

### ISSUE THREAD

**Issue by ThoMiDev** [tradle/react-native-udp#92]
When the phone's screen turned off, then I turned on it. The socket stop listening, so the app doesn't receive message any more.

**Comment by mvayngrib** [comment]
@ThoMiDev this is to be expected, apps don't run when you background them

you can do a couple of things:
- extend execution: https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/extending_your_app_s_background_execution_time
- periodic background tasks: https://developer.apple.com/documentation/backgroundtasks

closing as this is not an issue with this library

**Comment by ThoMiDev** [comment]
Can I re-bind the socket after the app coming from background?

**Comment by mvayngrib** [comment]
@ThoMiDev you should be able to, but you might want to listen for a 'close' and/or 'error' event on the first socket. You can also use the react-native built-in AppState module to detect coming back from background, and close/re-open any sockets

**Comment by ThoMiDev** [comment]
I have tried to close the socket and re-open it, but I got the error: `Socket is already bound`

**Comment by ThoMiDev** [comment]
const handleAppStateChange = (nextAppState: string) => {
        if (nextAppState === 'active') {
          socket.bind('0.0.0.0', (err: Error) => {
            console.warn('Connected Successfully?: ', err ? 'false' : 'true');
          });
        }
        else {
          socket.close();
        }
        console.warn(nextAppState);
    };

**Comment by mvayngrib** [comment]
@ThoMiDev i'll see if i can test it some time this week. If you get it working before then, please leave a comment about what you did :)
