### ISSUE TITLE
AndroidX (RN 0.60.5) not supported

### ISSUE THREAD

**Issue by Rapsssito** [tradle/react-native-udp#94]
When trying to generate an APK the compilation gets stuck with the following errors: https://github.com/rt2zz/react-native-contacts/issues/395#issuecomment-503428694
Possible fix:
https://github.com/rt2zz/react-native-contacts/issues/395#issuecomment-503808060

**Comment by mvayngrib** [comment]
@Rapsssito have u tried https://github.com/rt2zz/react-native-contacts/issues/395#issuecomment-506064542  ?

**Comment by Rapsssito** [comment]
Yeah, it works now!
